spring:
  output:
    ansi:
      enabled: always
---
spring:
  profiles:
    group:
      "local" : "local, jwt, oauth, aws"
    active : local

---
spring:
  config:
    activate:
      on-profile: "local"

  h2:
    console:
      enabled: false
#      path: /h2-console

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.63.31:3306/mogongdb?serverTimezone=UTC&characterEncoding=UTF-8
    username: abcgnd
    password: G8G8g8g8gnd123!

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
        show_sql: true

    hibernate:
      ddl-auto: update
---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
---
logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error
---
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB